### ISSUE TITLE
./inspectpacket.py fails with 'list index out of range' traceback

### ISSUE THREAD

**Issue by quarterturn** [souramoo/ReverseEngineeredMiLightBluetooth#1]
Running ./inspectpacket.py against a btsnoop_hci.log file results in the following:

Traceback (most recent call last):
  File "./inspectpacket.py", line 7, in <module>
    line = string.split(lines[0].rstrip('\n'), ' ')[7]
IndexError: list index out of range

**Comment by souramoo** [comment]
inspectpacket.py was never meant to parse btsnoop_lci.log files - it was meant to parse files in the style of things under the `commands/` folder.

Sorry for the messiness in decoding the id of the bulbs - I put this all together in an afternoon and I'd just pulled the id of the bulbs off the packets.

I'll get round to quickly reversing the id derivation function from the mac address so you won't need to use wireshark and snoop on your packets, and so wont even need to have the app installed...

**Comment by quarterturn** [comment]
Thanks for the reply. I have a slightly different style of "Mi-Bulb", so
I'm curious as to if your code works on it. My bulb's app appears to
have become abandonware which does not work under iOS 9, so if I can get
anything beyond on/off that will be great.

Alex


On Mon, Nov 2, 2015, at 07:48 AM, S. Mookerjee wrote:
> inspectpacket.py was never meant to parse btsnoop_lci.log files -
> it was meant to parse files in the style of things under the
> commands/ folder.


> Sorry for the messiness in decoding the id of the bulbs - I put this
> all together in an afternoon and I'd just pulled the id of the bulbs
> off the packets.


> I'll get round to quickly reversing the id derivation function from
> the mac address so you won't need to use wireshark and snoop on your
> packets, and so wont even need to have the app installed...


> — Reply to this email directly or view it on GitHub[1].


>

--
"The theater of noise is proof of our potential."
|\ |  (¯  \/ |¯\  |V| |\ ¯|¯ |¯) | \/ | | | |¯\ (¯   /¯  /\ |V|
|-||_ (_  /\ |_/ @| | |-| |  | \ | /\ |^| | |_/ (_ . \_  \/ | |
 
You won't find me on Facebook.
 
 


Links:

  1. https://github.com/moosd/ReverseEngineeredMiLightBluetooth/issues/1#issuecomment-153008253

**Comment by souramoo** [comment]
Even if my code doesn't work for your model of bulb, you should be able to use the same black-box approach I used to control the bulb without having much knowledge over the protocol itself. Here's what I did if you have some time free to play around:

I fetched a btsnoop_hci.log file before pressing any button in the app to something like `old.log`, and then another one afterwards to `new.log`. Then I opened up `old.log` in wireshark and made a note of the number of packets. I opened up `new.log`, skipped to the packets that came after the number of packets in `new.log`. Any commands to control the bulb must have been in these set of packets, the difference between the previous and current files.

Then you can use gatttool to send your own packets (remember to turn your bulb off if you fetched the packets to turn it on for example!), and perform a packet replay attack, where you can right click the packets one by one in wireshark, copy the payload as hex strings and stick it into a gatttool command like the files in `commands/` - keep replaying the packets one by one until your bulb does something.

Then you know that the data to control the bulb is present within the packet. You can do this for as many functions in the original app as you want without needing to understand the protocol.

Commands you'll need to have a play with this are:
`hcitool lescan` - to get the mac address of the bulb you want to talk to.
`gatttool -b $BULB_MAC --char-write-req -a 0x0012 -n $PAYLOAD` - to send packets back - replace $BULB_MAC and $PAYLOAD with appropriate values

Coincidentally, if you do get a payload that might work, you can copy it into the commands folder and use `inspectpacket.py` to see if it uses the same protocol structure that mine uses and to obtain the ids needed to use the rest of my code to do what you want with the bulb without relying on the app and my home automation framework (https://github.com/moosd/HomeAutomation) if you so wish

**Comment by souramoo** [comment]
Commit  f80022f adds the `getid.py` script. After running `hcitool lescan` you should get something like this:

```
$ sudo hcitool lescan
LE Scan ...
44:A6:E5:01:57:CF (unknown)
44:A6:E5:01:57:CF M129617E98C33A86E7
```

You have the mac address there on the left, and if you pass the string on the right beginning with M into getid.py:

```
$ ./getid.py M129617E98C33A86E7
BULB_ID1=18
BULB_ID2=150
```

It will calculate the bulb ids you need to talk to the bulb. Let me know how it goes, good luck! :)

**Comment by quarterturn** [comment]
Thank you! I will try it tomorrow.

Alex

> On Nov 2, 2015, at 4:48 PM, S. Mookerjee <notifications@github.com> wrote:
> 
> Commit f80022f <https://github.com/moosd/ReverseEngineeredMiLightBluetooth/commit/f80022f2df7e60c252f43c067d84b069f06018a3> adds the getid.py script. After running hcitool lescan you should get something like this:
> 
> $ sudo hcitool lescan
> LE Scan ...
> 44:A6:E5:01:57:CF (unknown)
> 44:A6:E5:01:57:CF M129617E98C33A86E7
> You have the mac address there on the left, and if you pass the string on the right beginning with M into getid.py:
> 
> $ ./getid.py M129617E98C33A86E7
> BULB_ID1=18
> BULB_ID2=150
> It will calculate the bulb ids you need to talk to the bulb. Let me know how it goes, good luck! :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/moosd/ReverseEngineeredMiLightBluetooth/issues/1#issuecomment-153167692>.
> 

“The right of the people to be secure in their persons, houses, papers, and
 effects, against unreasonable searches and seizures, shall not be violated,
 and no Warrants shall issue, but upon probable cause, supported by Oath
 or affirmation, and particularly describing the place to be searched,
 and the persons or things to be seized.”

US Constitution 4th Amendment - It's The Law

|\ |  (¯  \/ |¯\  |V| |\ ¯|¯ |¯) | \/ | | | |¯\ (¯   /¯  /\ |V|
|-||_ (_  /\ |_/ @| | |-| |  | \ | /\ |^| | |_/ (_ . \_  \/ | |
